#!/usr/bin/env python3
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parent
DOMAIN = 'https://fynzo.me/'
GUIDES=[
('blog-why-calorie-calculators-differ.html','Why Do Calorie Calculators Give Different Results?','Calorie estimates differ because equations, activity multipliers, rounding and personal energy expenditure are not identical.','Health guide',[('Different BMR equations','Mifflin-St Jeor and revised Harris-Benedict can produce different starting estimates.'),('Activity multipliers','Two websites can label activity levels differently, causing larger TDEE differences than the BMR formula.'),('Individual variation','Daily movement, body composition, sleep, health and food tracking can make real needs differ from a formula.')],'Use a calculator as a starting estimate, track a stable routine over time, and adjust with appropriate professional support when health circumstances require it.','calorie-calculator.html','Calculate BMR and TDEE'),
('blog-36-vs-60-month-loan.html','36 vs 60 Month Loan: Payment and Total Interest','Compare a 36-month and 60-month loan term to understand the trade-off between monthly payment and total scheduled interest.','Loan guide',[('36-month term','Usually produces a higher monthly payment and lower total interest when the rate and principal are unchanged.'),('60-month term','Usually produces a lower monthly payment and higher total interest.'),('Fair comparison','Use the same principal, rate, fees and payment timing for both terms.')],'A lower monthly payment does not automatically mean a lower-cost loan. Compare total repayment and confirm lender fees and APR.','loan-calculator.html','Compare loan terms'),
('blog-bmi-vs-body-fat.html','BMI vs Body Fat Percentage: What Each Estimate Means','BMI uses height and weight, while body-fat formulas attempt to estimate body composition from measurements. Both have limitations.','Health guide',[('BMI','Fast screening ratio based only on height and weight.'),('Body-fat estimate','Uses measurements and an equation, but tape placement and formula error affect the result.'),('Best use','Use repeated measurements consistently for general trend awareness, not diagnosis.')],'Neither result diagnoses health. Children, pregnancy, medical conditions and athletic body composition require appropriate context and qualified guidance.','body-fat-calculator.html','Compare BMI and body-fat tools'),
('blog-apr-vs-interest-rate.html','APR vs Interest Rate: What Borrowers Should Compare','Interest rate is the cost of borrowing principal, while APR can incorporate certain fees to provide a broader annualized comparison.','Loan guide',[('Interest rate','Used to calculate periodic interest on the principal.'),('APR','Can include eligible fees and costs under a defined calculation method.'),('Comparison','Compare offers with the same amount, term and assumptions, and review official disclosures.')],'A calculator estimate is not an official lender disclosure. Fee treatment and legal definitions can vary.','apr-calculator.html','Estimate APR'),
('blog-percentage-change-vs-points.html','Percentage Change vs Percentage Points','Percentage change measures relative movement, while percentage points measure the arithmetic difference between two percentage values.','Percentage guide',[('Percentage points','A rise from 20% to 25% is 5 percentage points.'),('Percentage change','The same rise is a 25% relative increase because 5 divided by 20 equals 25%.'),('Use the right label','Reporting a percentage increase as percentage points can materially change the meaning.')],'Always identify the original value and whether the question asks for a relative change or a direct difference.','percentage-calculator.html','Calculate percentage change')]

def ld(*objs):
    return ''.join(
        '<script type="application/ld+json">\n'
        + json.dumps(obj, ensure_ascii=False, separators=(',', ':'))
        + '\n</script>'
        for obj in objs
        if obj
    )


def build(g):
 slug,title,desc,cat,sections,closing,calc,cta=g
 sec=''.join(f'<h2>{escape(h)}</h2><p>{escape(p)}</p>' for h,p in sections)
 schema=ld(
     {"@context":"https://schema.org","@type":"Article","headline":title,"description":desc,"image":DOMAIN+"og-default.png","datePublished":"2026-08-01","dateModified":"2026-08-01","author":{"@type":"Person","name":"Yasser Chahir"},"publisher":{"@type":"Organization","name":"Fynzo","url":DOMAIN,"logo":{"@type":"ImageObject","url":DOMAIN+"logo-icon.svg"}},"mainEntityOfPage":DOMAIN+slug,"inLanguage":"en","isAccessibleForFree":True},
     {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":DOMAIN},{"@type":"ListItem","position":2,"name":"Blog","item":DOMAIN+"blog.html"},{"@type":"ListItem","position":3,"name":title,"item":DOMAIN+slug}]}
 )
 html=f'''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Fynzo</title><meta name="description" content="{escape(desc)}"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="{DOMAIN}{slug}"><link rel="alternate" hreflang="en" href="{DOMAIN}{slug}"><link rel="alternate" hreflang="x-default" href="{DOMAIN}{slug}"><link rel="icon" href="favicon.svg"><meta property="og:type" content="article"><meta property="og:site_name" content="Fynzo"><meta property="og:title" content="{escape(title)} | Fynzo"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{DOMAIN}{slug}"><meta property="og:image" content="{DOMAIN}og-default.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{escape(title)} | Fynzo"><meta name="twitter:description" content="{escape(desc)}"><meta name="twitter:image" content="{DOMAIN}og-default.png"><meta name="twitter:image:alt" content="{escape(title)}"><link rel="stylesheet" href="styles.css">{schema}</head><body><a class="skip-link" href="#main-content">Skip to main content</a><header class="site-header"><nav aria-label="Primary navigation"><a class="brand" href="index.html">Fynzo</a><div class="nav-links"><a href="index.html#tools">Calculators</a><a href="blog.html">Guides</a><a href="about.html">About</a></div></nav></header><main id="main-content"><article class="article"><div class="article-head"><div class="post-cat">{escape(cat)}</div><h1>{escape(title)}</h1><div class="meta"><span>August 1, 2026</span><span>Reviewed by Yasser Chahir</span></div></div><p class="article-lead">{escape(desc)}</p>{sec}<h2>Practical takeaway</h2><p>{escape(closing)}</p><div class="cta-box"><h3>Run your own numbers</h3><p>Use the related Fynzo calculator with consistent assumptions and compare the full result.</p><a class="btn" href="{calc}">{escape(cta)}</a></div><h2>Review note</h2><p>This guide is educational and should not replace medical, financial, legal or tax guidance. Last reviewed August 1, 2026.</p></article></main><footer class="site-footer"><div class="wrap"><div class="foot-bottom">© 2026 Fynzo · Educational information only.</div></div></footer><script defer src="fynzo.js"></script></body></html>'''
 (ROOT/slug).write_text(html,encoding='utf-8')
for g in GUIDES: build(g)
print('Built',len(GUIDES),'high-intent supporting guides.')
