#!/usr/bin/env python3
from pathlib import Path
from html import escape
ROOT=Path(__file__).resolve().parent
DOMAIN='https://fynzo.me/'

def page(slug,title,desc,h1,eyebrow,fields,result_js,content,faq,related):
    field_html=''.join(fields)
    faq_html=''.join(f'<div class="faq-item"><div class="faq-q"><h3>{escape(q)}</h3><span>+</span></div><div class="faq-a">{escape(a)}</div></div>' for q,a in faq)
    related_html=''.join(f'<a class="silo-card" href="{u}"><span>{escape(t)}</span></a>' for u,t in related)
    html=f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Fynzo</title><meta name="description" content="{escape(desc)}"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="{DOMAIN}{slug}"><link rel="icon" href="favicon.svg"><link rel="manifest" href="manifest.json"><meta name="theme-color" content="#0b1020"><meta property="og:type" content="website"><meta property="og:site_name" content="Fynzo"><meta property="og:title" content="{escape(title)} | Fynzo"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{DOMAIN}{slug}"><meta property="og:image" content="{DOMAIN}og-default.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{escape(title)} | Fynzo"><meta name="twitter:description" content="{escape(desc)}"><meta name="twitter:image" content="{DOMAIN}og-default.png"><link rel="stylesheet" href="styles.css"></head><body><a class="skip-link" href="#main-content">Skip to main content</a><header class="site-header"><nav aria-label="Primary navigation"><a class="brand" href="index.html" aria-label="Fynzo home">Fynzo</a><div class="nav-links"><a href="index.html#tools">Calculators</a><a href="blog.html">Guides</a><a href="about.html">About</a></div></nav></header><nav class="crumb" aria-label="Breadcrumb"><a href="index.html">Home</a> · <a href="index.html#finance-calculators">Calculators</a> · {escape(h1)}</nav><main id="main-content"><div class="page-head"><div class="wrap"><div class="eyebrow">{escape(eyebrow)}</div><h1>{escape(h1)}</h1><p class="updated">{escape(desc)}</p></div></div><section class="sec"><div class="wrap"><div class="calc-wrap"><form id="fx" aria-label="{escape(h1)}">{field_html}<p id="err" role="alert" class="calc-error" hidden></p></form><div id="res" role="status" aria-live="polite" aria-atomic="true"></div></div></div></section><section class="sec"><div class="wrap"><div class="doc">{content}</div></div></section><section class="sec"><div class="wrap"><h2>Frequently asked questions</h2><div class="faq">{faq_html}</div></div></section><section class="silo"><div class="wrap"><h2 class="silo-h">Related tools and guides</h2><div class="silo-grid">{related_html}</div></div></section></main><footer class="site-footer"><div class="wrap"><div class="foot-bottom">© 2026 Fynzo · Educational estimates only · Calculations run in your browser.</div></div></footer><script defer src="fynzo.js"></script><script>{result_js}</script><script defer src="advanced.js"></script><script defer src="tool-actions.js"></script></body></html>'''
    (ROOT/slug).write_text(html,encoding='utf-8')

field=lambda label,id,value,typ='number',step='any',extra='': f'<div class="field"><label for="{id}">{label}</label><input id="{id}" data-k="{id}" type="{typ}" value="{value}" step="{step}" {extra}></div>'

page('mortgage-total-cost-calculator.html','Mortgage Calculator with Taxes, Insurance & PMI','Estimate the total monthly mortgage cost including principal, interest, property tax, home insurance, PMI and HOA fees.','Mortgage Calculator with Taxes, Insurance and PMI','Full housing cost calculator',[
 field('Home price ($)','price','350000','number','1000','min="1"'),field('Down payment ($)','down','70000','number','1000','min="0"'),field('Annual interest rate (%)','rate','6.25','number','0.01','min="0"'),field('Loan term (years)','years','30','number','1','min="1"'),field('Annual property tax ($)','tax','4200','number','100','min="0"'),field('Annual home insurance ($)','insurance','1800','number','100','min="0"'),field('Annual PMI rate (%)','pmi','0','number','0.01','min="0"'),field('Monthly HOA fee ($)','hoa','0','number','10','min="0"')],
'''function n(id){return Number(document.getElementById(id).value)}function money(x){return x.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2})}function calc(){var p=n('price'),d=n('down'),a=n('rate'),y=n('years'),tax=n('tax'),ins=n('insurance'),pmi=n('pmi'),hoa=n('hoa'),e=document.getElementById('err');if(![p,d,a,y,tax,ins,pmi,hoa].every(Number.isFinite)||p<=0||d<0||d>=p||a<0||y<=0||tax<0||ins<0||pmi<0||hoa<0){e.hidden=false;e.textContent='Enter valid non-negative values. Down payment must be lower than the home price.';document.getElementById('res').innerHTML='';return}e.hidden=true;var principal=p-d,r=a/1200,m=y*12,pi=r===0?principal/m:principal*r*Math.pow(1+r,m)/(Math.pow(1+r,m)-1),monthlyTax=tax/12,monthlyIns=ins/12,monthlyPmi=principal*(pmi/100)/12,total=pi+monthlyTax+monthlyIns+monthlyPmi+hoa;document.getElementById('res').innerHTML='<div class="rbig">'+money(total)+'/month</div><div class="rlabel">Estimated total monthly housing cost</div><div class="rrow"><span>Principal and interest</span><span>'+money(pi)+'</span></div><div class="rrow"><span>Property tax</span><span>'+money(monthlyTax)+'</span></div><div class="rrow"><span>Home insurance</span><span>'+money(monthlyIns)+'</span></div><div class="rrow"><span>PMI</span><span>'+money(monthlyPmi)+'</span></div><div class="rrow"><span>HOA</span><span>'+money(hoa)+'</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
'''<h2>What the total monthly mortgage cost includes</h2><p>Many mortgage estimates show principal and interest only. This calculator adds the property tax, home insurance, optional PMI and HOA amounts entered by the user. Local tax assessments, insurance quotes and lender rules can change the real total.</p><h2>Worked example</h2><p>For a $350,000 home with $70,000 down, a 6.25% fixed rate and a 30-year term, the financed principal is $280,000. Adding annual tax, insurance and optional PMI gives a more complete monthly planning estimate than principal and interest alone.</p><h2>Important limitations</h2><p>The result is not a lender quote and does not include every fee, utility, repair or maintenance cost. Verify property-specific tax and insurance information before making a decision.</p>''',
[('Does the payment include property tax and insurance?','Yes, when annual amounts are entered. The calculator converts them to monthly estimates.'),('What is PMI?','Private mortgage insurance may apply to some loans with a smaller down payment. The actual rate and cancellation rules depend on the loan.'),('Does HOA count as part of the mortgage?','HOA is not part of the loan payment, but it is included here as a recurring housing cost.'),('Why can a lender quote differ?','Lenders can use property-specific taxes, insurance, escrow rules, fees and eligibility terms that a general calculator cannot know.')],
[('mortgage-calculator.html','Principal and interest mortgage calculator'),('extra-mortgage-payment-calculator.html','Extra mortgage payment calculator'),('mortgage-guides.html','Mortgage guides')])

page('mortgage-recast-calculator.html','Mortgage Recast Calculator: New Payment After Lump Sum','Estimate a new mortgage payment after a principal lump-sum recast using the remaining balance, rate and remaining term.','Mortgage Recast Calculator','Mortgage planning calculator',[
 field('Current principal balance ($)','balance','300000','number','1000','min="1"'),field('Annual interest rate (%)','rate','4','number','0.01','min="0"'),field('Remaining term (months)','months','300','number','1','min="1"'),field('Lump-sum principal payment ($)','lump','25000','number','1000','min="0"'),field('Recast fee ($)','fee','250','number','10','min="0"')],
'''function n(id){return Number(document.getElementById(id).value)}function pay(p,a,m){var r=a/1200;return r===0?p/m:p*r*Math.pow(1+r,m)/(Math.pow(1+r,m)-1)}function money(x){return x.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2})}function calc(){var b=n('balance'),a=n('rate'),m=n('months'),l=n('lump'),f=n('fee'),e=document.getElementById('err');if(![b,a,m,l,f].every(Number.isFinite)||b<=0||a<0||m<=0||l<0||l>=b||f<0){e.hidden=false;e.textContent='Enter valid values. The lump-sum payment must be lower than the current balance.';document.getElementById('res').innerHTML='';return}e.hidden=true;var old=pay(b,a,m),nw=pay(b-l,a,m),save=old-nw,breakeven=save>0?f/save:0;document.getElementById('res').innerHTML='<div class="rbig">'+money(nw)+'/month</div><div class="rlabel">Estimated payment after recast</div><div class="rrow"><span>Current calculated payment</span><span>'+money(old)+'</span></div><div class="rrow"><span>Monthly reduction</span><span>'+money(save)+'</span></div><div class="rrow"><span>New principal</span><span>'+money(b-l)+'</span></div><div class="rrow"><span>Fee break-even</span><span>'+(breakeven?breakeven.toFixed(1)+' months':'N/A')+'</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
'''<h2>Recast versus refinance</h2><p>A recast applies a principal lump-sum payment and recalculates the payment over the existing remaining term at the existing rate. A refinance replaces the loan and can change the rate, term and fees.</p><h2>Key assumption</h2><p>The remaining months must be the actual remaining term. Do not reset the term to 360 months unless a new 30-year loan is being modeled.</p><h2>Limitations</h2><p>Not every loan is eligible for recasting. Minimum principal payments, waiting periods and fees depend on the lender and contract.</p>''',
[('Does a recast change the interest rate?','Normally no. It recalculates the payment using the existing rate and remaining term.'),('Does a recast shorten the loan term?','The calculator assumes the scheduled remaining term stays unchanged.'),('Is recasting the same as refinancing?','No. Refinancing creates a new loan, while a recast generally modifies the payment schedule of the existing loan.'),('Can every mortgage be recast?','No. Eligibility and fees depend on the loan and lender.')],
[('mortgage-total-cost-calculator.html','Mortgage total monthly cost'),('extra-mortgage-payment-calculator.html','Extra payment calculator'),('mortgage-guides.html','Mortgage guides')])

page('pay-raise-calculator.html','Pay Raise Calculator: Increase, New Salary & Monthly Difference','Calculate a pay raise percentage, new annual salary and monthly, biweekly and weekly gross-pay differences.','Pay Raise Calculator','Salary calculator',[
 field('Current annual salary ($)','salary','50000','number','100','min="0"'),field('Raise (%)','raise','5','number','0.1','min="-100"'),field('Annual bonus change ($)','bonus','0','number','100')],
'''function n(id){return Number(document.getElementById(id).value)}function money(x){return x.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2})}function calc(){var s=n('salary'),r=n('raise'),b=n('bonus'),e=document.getElementById('err');if(![s,r,b].every(Number.isFinite)||s<0||r<-100){e.hidden=false;e.textContent='Enter a non-negative salary and a raise greater than or equal to -100%.';document.getElementById('res').innerHTML='';return}e.hidden=true;var base=s*(1+r/100),nw=base+b,d=nw-s;document.getElementById('res').innerHTML='<div class="rbig">'+money(nw)+'</div><div class="rlabel">New annual gross pay</div><div class="rrow"><span>Annual difference</span><span>'+money(d)+'</span></div><div class="rrow"><span>Monthly difference</span><span>'+money(d/12)+'</span></div><div class="rrow"><span>Biweekly difference</span><span>'+money(d/26)+'</span></div><div class="rrow"><span>Weekly difference</span><span>'+money(d/52)+'</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
'''<h2>How to calculate a pay raise</h2><p>Multiply the current salary by the raise percentage, then add the increase to the current salary. A 5% raise on $50,000 is $2,500, producing $52,500 before any additional bonus change.</p><h2>Gross pay limitation</h2><p>The result is gross pay. Taxes, benefits, retirement deductions and payroll schedules can change take-home pay.</p>''',
[('How much is a 5% raise on $50,000?','$2,500 per year, before taxes and other deductions.'),('Does the calculator include tax?','No. It calculates gross pay only.'),('Can I enter a pay cut?','Yes. Enter a negative percentage down to -100%.'),('Why is biweekly pay divided by 26?','A common biweekly schedule has 26 pay periods per year.')],
[('hourly-to-salary-calculator.html','Hourly to salary calculator'),('income-tax-calculator.html','Income tax estimate'),('percentage-calculator.html','Percentage calculator')])

page('work-hours-calculator.html','Work Hours Calculator: Time Between Shifts & Breaks','Calculate paid work hours between a start and end time after subtracting an unpaid break, including overnight shifts.','Work Hours Calculator','Time and work calculator',[
 field('Shift start','start','09:00','time','any'),field('Shift end','end','17:30','time','any'),field('Unpaid break (minutes)','breaks','30','number','1','min="0"'),field('Hourly rate ($, optional)','rate','0','number','0.01','min="0"')],
'''function mins(v){var a=v.split(':').map(Number);return a[0]*60+a[1]}function n(id){return Number(document.getElementById(id).value)}function money(x){return x.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2})}function calc(){var a=document.getElementById('start').value,b=document.getElementById('end').value,br=n('breaks'),rate=n('rate'),e=document.getElementById('err');if(!a||!b||![br,rate].every(Number.isFinite)||br<0||rate<0){e.hidden=false;e.textContent='Enter valid start and end times and non-negative break and rate values.';document.getElementById('res').innerHTML='';return}var total=mins(b)-mins(a);if(total<0)total+=1440;if(br>=total){e.hidden=false;e.textContent='The unpaid break must be shorter than the shift.';document.getElementById('res').innerHTML='';return}e.hidden=true;var paid=total-br,h=paid/60;document.getElementById('res').innerHTML='<div class="rbig">'+Math.floor(paid/60)+'h '+(paid%60)+'m</div><div class="rlabel">Paid work time</div><div class="rrow"><span>Total shift</span><span>'+Math.floor(total/60)+'h '+(total%60)+'m</span></div><div class="rrow"><span>Unpaid break</span><span>'+br+' minutes</span></div><div class="rrow"><span>Decimal hours</span><span>'+h.toFixed(2)+'</span></div><div class="rrow"><span>Gross pay</span><span>'+(rate?money(h*rate):'Add hourly rate')+'</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
'''<h2>How overnight shifts are handled</h2><p>If the end time is earlier than the start time, the calculator treats the shift as crossing midnight. A 10:00 PM to 6:00 AM shift is eight hours before breaks.</p><h2>Worked example</h2><p>A 9:00 AM to 5:30 PM shift is 8 hours 30 minutes. After a 30-minute unpaid break, paid time is 8 hours.</p>''',
[('Does the calculator support overnight shifts?','Yes. An end time earlier than the start time is treated as the following day.'),('Are breaks included?','The entered unpaid break is subtracted from the total shift.'),('What are decimal hours?','Decimal hours express minutes as a fraction of an hour, such as 7.5 hours for 7 hours 30 minutes.'),('Does gross pay include overtime or tax?','No. The optional pay estimate is hours multiplied by the entered rate.')],
[('hourly-to-salary-calculator.html','Hourly to salary calculator'),('business-days-calculator.html','Business days calculator'),('time-duration-calculator.html','Time duration calculator')])

print('Built 4 high-intent opportunity calculators.')
