#!/usr/bin/env python3
from pathlib import Path
from html import escape
ROOT=Path(__file__).resolve().parent
DOMAIN='https://fynzo.me/'

def fld(label,id,val,typ='number',step='any',extra=''):
 return f'<div class="field"><label for="{id}">{escape(label)}</label><input id="{id}" data-k="{id}" type="{typ}" value="{val}" step="{step}" {extra}></div>'

def page(slug,title,desc,h1,eyebrow,fields,js,sections,faqs,related):
 faq=''.join(f'<div class="faq-item"><div class="faq-q"><h3>{escape(q)}</h3><span>+</span></div><div class="faq-a">{escape(a)}</div></div>' for q,a in faqs)
 rel=''.join(f'<a class="silo-card" href="{u}"><span>{escape(t)}</span></a>' for u,t in related)
 content=''.join(f'<h2>{escape(h)}</h2><p>{escape(p)}</p>' for h,p in sections)
 html=f'''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Fynzo</title><meta name="description" content="{escape(desc)}"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="{DOMAIN}{slug}"><link rel="icon" href="favicon.svg"><link rel="manifest" href="manifest.json"><meta name="theme-color" content="#0b1020"><meta property="og:type" content="website"><meta property="og:site_name" content="Fynzo"><meta property="og:title" content="{escape(title)} | Fynzo"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{DOMAIN}{slug}"><meta property="og:image" content="{DOMAIN}og-default.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{escape(title)} | Fynzo"><meta name="twitter:description" content="{escape(desc)}"><meta name="twitter:image" content="{DOMAIN}og-default.png"><link rel="stylesheet" href="styles.css"></head><body><a class="skip-link" href="#main-content">Skip to main content</a><header class="site-header"><nav aria-label="Primary navigation"><a class="brand" href="index.html">Fynzo</a><div class="nav-links"><a href="index.html#tools">Calculators</a><a href="blog.html">Guides</a><a href="about.html">About</a></div></nav></header><nav class="crumb" aria-label="Breadcrumb"><a href="index.html">Home</a> · <a href="index.html#tools">Calculators</a> · {escape(h1)}</nav><div class="page-head" id="main-content" role="main"><div class="wrap"><div class="eyebrow">{escape(eyebrow)}</div><h1>{escape(h1)}</h1><p class="updated">{escape(desc)}</p></div></div><section class="sec" style="padding-top:36px"><div class="wrap"><div class="calc-wrap"><form id="fx" aria-label="{escape(h1)}">{''.join(fields)}<p id="err" class="calc-error" role="alert" hidden></p></form><div><div id="res" class="result" role="status" aria-live="polite" aria-atomic="true"></div></div></div></div></section><section class="sec"><div class="wrap"><div class="doc">{content}</div></div></section><section class="sec"><div class="wrap"><h2>Frequently asked questions</h2><div class="faq">{faq}</div></div></section><section class="silo"><div class="wrap"><h2 class="silo-h">Related tools and guides</h2><div class="silo-grid">{rel}</div></div></section><footer class="site-footer"><div class="wrap"><div class="foot-bottom">© 2026 Fynzo · Educational estimates only · Calculations run in your browser.</div></div></footer><script defer src="fynzo.js"></script><script>{js}</script><script defer src="advanced.js"></script><script defer src="tool-actions.js"></script><script defer src="pdf-report-v2.js"></script></body></html>'''
 (ROOT/slug).write_text(html,encoding='utf-8')

common="function n(i){return Number(document.getElementById(i).value)}function money(x){return x.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2})}function bad(v){return !v.every(Number.isFinite)}"

page('auto-loan-calculator.html','Auto Loan Calculator with Tax, Fees & Trade-In','Estimate a car payment including vehicle price, trade-in, down payment, sales tax, fees, rate and term.','Auto Loan Calculator with Tax, Fees and Trade-In','Auto finance calculator',[
 fld('Vehicle price ($)','price','30000','number','100','min="1"'),fld('Down payment ($)','down','3000','number','100','min="0"'),fld('Trade-in value ($)','trade','0','number','100','min="0"'),fld('Sales tax (%)','tax','6','number','0.01','min="0"'),fld('Fees ($)','fees','500','number','10','min="0"'),fld('Interest rate (%)','rate','7','number','0.01','min="0"'),fld('Loan term (months)','months','60','number','1','min="1"')],common+'''function calc(){let p=n('price'),d=n('down'),t=n('trade'),x=n('tax'),f=n('fees'),a=n('rate'),m=n('months'),e=document.getElementById('err');if(bad([p,d,t,x,f,a,m])||p<=0||d<0||t<0||d+t>=p||x<0||f<0||a<0||m<=0){e.hidden=false;e.textContent='Enter valid values. Down payment plus trade-in must be lower than the vehicle price.';res.innerHTML='';return}e.hidden=true;let principal=(p-t)*(1+x/100)+f-d,r=a/1200,pay=r===0?principal/m:principal*r*Math.pow(1+r,m)/(Math.pow(1+r,m)-1),interest=pay*m-principal;res.innerHTML='<div class="rlabel">Monthly car payment</div><div class="rbig">'+money(pay)+'</div><div class="rrow"><span>Amount financed</span><span>'+money(principal)+'</span></div><div class="rrow"><span>Total interest</span><span>'+money(interest)+'</span></div><div class="rrow"><span>Total loan payments</span><span>'+money(pay*m)+'</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
[('What this calculator includes','The financed amount can include sales tax and fees after subtracting the trade-in and cash down payment.'),('Comparison tip','Compare the total interest and total payment, not only the monthly payment. A longer term can reduce the payment while increasing borrowing cost.'),('Important limitation','Dealer calculations can treat trade-ins, tax, rebates and fees differently. Confirm the purchase order and lender disclosure.')],
[('Does the calculation include sales tax?','Yes, using the entered percentage and the displayed formula assumptions.'),('Can I include a trade-in?','Yes. The trade-in value reduces the price before the illustrative sales-tax calculation.'),('Does a longer term cost more?','At the same rate and principal, a longer term usually lowers the monthly payment and increases total interest.'),('Is this a lender quote?','No. It is an educational estimate.')],[('loan-comparison-calculator.html','Compare two loan offers'),('loan-calculator.html','Personal loan calculator'),('budget-percentage-calculator.html','Budget calculator')])

page('credit-card-payoff-calculator.html','Credit Card Payoff Calculator: Time & Interest','Estimate credit card payoff time, total interest and the effect of an extra monthly payment.','Credit Card Payoff Calculator','Debt calculator',[
 fld('Current balance ($)','balance','5000','number','10','min="0.01"'),fld('APR (%)','apr','22','number','0.01','min="0"'),fld('Monthly payment ($)','payment','200','number','1','min="0.01"'),fld('Extra monthly payment ($)','extra','50','number','1','min="0"')],common+'''function solve(b,apr,p){let r=apr/1200,i=0,total=0;while(b>0.005&&i<1200){let interest=b*r;if(p<=interest)return null;let paid=Math.min(p,b+interest);b=b+interest-paid;total+=interest;i++}return {months:i,interest:total}}function calc(){let b=n('balance'),a=n('apr'),p=n('payment'),x=n('extra'),e=document.getElementById('err');if(bad([b,a,p,x])||b<=0||a<0||p<=0||x<0){e.hidden=false;e.textContent='Enter a positive balance and payment with non-negative APR and extra payment.';res.innerHTML='';return}let base=solve(b,a,p),fast=solve(b,a,p+x);if(!base||!fast){e.hidden=false;e.textContent='The payment must be greater than the first month interest.';res.innerHTML='';return}e.hidden=true;res.innerHTML='<div class="rlabel">Payoff time with extra payment</div><div class="rbig">'+fast.months+' months</div><div class="rrow"><span>Interest with extra payment</span><span>'+money(fast.interest)+'</span></div><div class="rrow"><span>Months saved</span><span>'+(base.months-fast.months)+'</span></div><div class="rrow"><span>Interest saved</span><span>'+money(base.interest-fast.interest)+'</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
[('How payoff is estimated','The calculator applies monthly interest, subtracts the entered payment and repeats until the balance reaches zero.'),('Minimum-payment warning','A payment that does not exceed monthly interest cannot reduce the balance in this simplified model.'),('Important limitation','Real cards can use daily compounding, variable APRs, fees and changing minimum payments.')],
[('How long will it take to pay off a credit card?','It depends on the balance, APR, payment and whether new charges are added.'),('Does an extra payment save interest?','Usually yes because the balance declines faster.'),('What if the payment is below monthly interest?','The simplified payoff calculation cannot produce a payoff date.'),('Does this include new purchases?','No. It assumes no new charges or fees.')],[('debt-payoff-calculator.html','Compare debt payoff strategies'),('apr-calculator.html','APR calculator'),('emergency-fund-calculator.html','Emergency fund calculator')])

page('retirement-savings-calculator.html','Retirement Savings Calculator: Projection & Goal Gap','Project retirement savings from current balance, monthly contributions, time, return and target.','Retirement Savings Calculator','Long-term savings calculator',[
 fld('Current age','age','30','number','1','min="18"'),fld('Retirement age','retire','65','number','1','min="19"'),fld('Current savings ($)','current','20000','number','100','min="0"'),fld('Monthly contribution ($)','monthly','500','number','10','min="0"'),fld('Expected annual return (%)','rate','6','number','0.1','min="0"'),fld('Target balance ($)','target','1000000','number','1000','min="0"')],common+'''function calc(){let age=n('age'),ret=n('retire'),c=n('current'),pm=n('monthly'),a=n('rate'),target=n('target'),e=document.getElementById('err');if(bad([age,ret,c,pm,a,target])||age<18||ret<=age||c<0||pm<0||a<0||target<0){e.hidden=false;e.textContent='Enter valid ages and non-negative money and return values.';res.innerHTML='';return}e.hidden=true;let months=(ret-age)*12,r=a/1200,fv=c*Math.pow(1+r,months)+(r===0?pm*months:pm*(Math.pow(1+r,months)-1)/r),contrib=c+pm*months,gap=Math.max(0,target-fv);res.innerHTML='<div class="rlabel">Projected retirement balance</div><div class="rbig">'+money(fv)+'</div><div class="rrow"><span>Total contributions</span><span>'+money(contrib)+'</span></div><div class="rrow"><span>Projected growth</span><span>'+money(fv-contrib)+'</span></div><div class="rrow"><span>Target gap</span><span>'+money(gap)+'</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
[('Projection method','The calculator compounds the current balance and assumes equal end-of-month contributions at a constant rate.'),('Use scenarios','Test conservative, moderate and optimistic return assumptions instead of relying on one forecast.'),('Important limitation','Returns are not guaranteed. Fees, taxes, inflation, withdrawals and contribution changes can materially change the outcome.')],
[('How much do I need to retire?','The answer depends on spending, retirement duration, inflation, other income and personal circumstances.'),('Is the return guaranteed?','No. The rate is only an assumption.'),('Does the result include inflation?','No. The target and projection are shown in nominal currency values.'),('When are monthly contributions added?','The formula assumes end-of-month contributions.')],[('compound-interest-calculator.html','Compound interest calculator'),('savings-goal-calculator.html','Savings goal calculator'),('emergency-fund-calculator.html','Emergency fund calculator')])

page('home-affordability-calculator.html','Home Affordability Calculator by Income & Debt','Estimate an affordable home price from income, debts, down payment, rate, term, tax, insurance and DTI.','Home Affordability Calculator','Home buying calculator',[
 fld('Gross monthly income ($)','income','7000','number','100','min="1"'),fld('Monthly debt payments ($)','debt','700','number','10','min="0"'),fld('Down payment ($)','down','60000','number','1000','min="0"'),fld('Interest rate (%)','rate','6.25','number','0.01','min="0"'),fld('Loan term (years)','years','30','number','1','min="1"'),fld('Housing DTI limit (%)','dti','28','number','0.1','min="1" max="60"'),fld('Monthly tax and insurance ($)','costs','500','number','10','min="0"')],common+'''function calc(){let inc=n('income'),debt=n('debt'),down=n('down'),a=n('rate'),y=n('years'),dti=n('dti'),cost=n('costs'),e=document.getElementById('err');if(bad([inc,debt,down,a,y,dti,cost])||inc<=0||debt<0||down<0||a<0||y<=0||dti<=0||cost<0){e.hidden=false;e.textContent='Enter valid income, term and non-negative cost values.';res.innerHTML='';return}let budget=inc*dti/100-debt-cost;if(budget<=0){e.hidden=false;e.textContent='The selected DTI budget is fully used by debts and housing costs.';res.innerHTML='';return}e.hidden=true;let r=a/1200,m=y*12,principal=r===0?budget*m:budget*(Math.pow(1+r,m)-1)/(r*Math.pow(1+r,m)),price=principal+down;res.innerHTML='<div class="rlabel">Estimated affordable home price</div><div class="rbig">'+money(price)+'</div><div class="rrow"><span>Estimated loan principal</span><span>'+money(principal)+'</span></div><div class="rrow"><span>Principal and interest budget</span><span>'+money(budget)+'/mo</span></div><div class="rrow"><span>Total housing budget</span><span>'+money(budget+cost)+'/mo</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
[('How the estimate works','The calculator applies the selected housing DTI limit, subtracts entered debts and housing costs, then converts the remaining payment budget into a loan principal.'),('Use a range','Try several DTI limits and cost assumptions. A maximum approval amount is not necessarily a comfortable budget.'),('Important limitation','Lenders can use different DTI rules, credit standards, reserves, rates and property costs.')],
[('What is DTI?','Debt-to-income ratio compares recurring monthly debt obligations with gross monthly income.'),('Does this guarantee approval?','No. It is an educational estimate.'),('Why include tax and insurance?','Those costs reduce the payment budget available for principal and interest.'),('Should I borrow the maximum?','Affordability also depends on savings, repairs, lifestyle and income stability.')],[('mortgage-total-cost-calculator.html','Mortgage with taxes and insurance'),('debt-to-income-calculator.html','Debt-to-income calculator'),('savings-goal-calculator.html','Down payment savings goal')])

page('loan-comparison-calculator.html','Loan Comparison Calculator: Payment, Fees & Total Cost','Compare two loan offers by rate, term, fees, monthly payment and total repayment.','Loan Comparison Calculator','Loan comparison tool',[
 fld('Loan amount ($)','amount','20000','number','100','min="1"'),fld('Loan A rate (%)','rateA','7','number','0.01','min="0"'),fld('Loan A term (months)','monthsA','36','number','1','min="1"'),fld('Loan A fees ($)','feesA','200','number','10','min="0"'),fld('Loan B rate (%)','rateB','8','number','0.01','min="0"'),fld('Loan B term (months)','monthsB','60','number','1','min="1"'),fld('Loan B fees ($)','feesB','0','number','10','min="0"')],common+'''function pay(p,a,m){let r=a/1200;return r===0?p/m:p*r*Math.pow(1+r,m)/(Math.pow(1+r,m)-1)}function calc(){let p=n('amount'),a=n('rateA'),ma=n('monthsA'),fa=n('feesA'),b=n('rateB'),mb=n('monthsB'),fb=n('feesB'),e=document.getElementById('err');if(bad([p,a,ma,fa,b,mb,fb])||p<=0||a<0||ma<=0||fa<0||b<0||mb<=0||fb<0){e.hidden=false;e.textContent='Enter a positive amount and terms with non-negative rates and fees.';res.innerHTML='';return}e.hidden=true;let pa=pay(p,a,ma),pb=pay(p,b,mb),ta=pa*ma+fa,tb=pb*mb+fb,w=ta<tb?'Loan A':'Loan B';res.innerHTML='<div class="rlabel">Lower estimated total cost</div><div class="rbig">'+w+'</div><div class="rrow"><span>Loan A payment / total</span><span>'+money(pa)+' / '+money(ta)+'</span></div><div class="rrow"><span>Loan B payment / total</span><span>'+money(pb)+' / '+money(tb)+'</span></div><div class="rrow"><span>Total cost difference</span><span>'+money(Math.abs(ta-tb))+'</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
[('Compare like with like','Use the same principal and include known mandatory fees for both offers.'),('Payment versus total cost','The offer with the lower monthly payment can still have the higher total cost.'),('Important limitation','APR disclosures can use defined fee treatment. Compare official lender documents before choosing an offer.')],
[('Can I compare 36 and 60 months?','Yes. Enter the terms and rates for each offer.'),('Are fees included?','The entered fees are added to total repayment for comparison.'),('Is the lower payment always better?','No. Review total cost and affordability together.'),('Does this calculate APR?','No. Use the APR calculator for an annualized fee-inclusive estimate.')],[('loan-calculator.html','Loan payment calculator'),('apr-calculator.html','APR calculator'),('credit-card-payoff-calculator.html','Credit card payoff calculator')])

page('net-worth-calculator.html','Net Worth Calculator: Assets Minus Liabilities','Calculate personal net worth by adding assets and subtracting mortgages, loans, credit cards and other debts.','Net Worth Calculator','Personal finance calculator',[
 fld('Cash and savings ($)','cash','10000','number','100','min="0"'),fld('Investments ($)','invest','25000','number','100','min="0"'),fld('Property and vehicles ($)','property','200000','number','1000','min="0"'),fld('Other assets ($)','otherA','0','number','100','min="0"'),fld('Mortgage balance ($)','mortgage','150000','number','1000','min="0"'),fld('Loans ($)','loans','10000','number','100','min="0"'),fld('Credit cards ($)','cards','3000','number','10','min="0"'),fld('Other debts ($)','otherD','0','number','100','min="0"')],common+'''function calc(){let vals=['cash','invest','property','otherA','mortgage','loans','cards','otherD'].map(n),e=document.getElementById('err');if(bad(vals)||vals.some(x=>x<0)){e.hidden=false;e.textContent='Enter non-negative values for assets and debts.';res.innerHTML='';return}e.hidden=true;let assets=vals.slice(0,4).reduce((a,b)=>a+b,0),debts=vals.slice(4).reduce((a,b)=>a+b,0),net=assets-debts;res.innerHTML='<div class="rlabel">Estimated net worth</div><div class="rbig">'+money(net)+'</div><div class="rrow"><span>Total assets</span><span>'+money(assets)+'</span></div><div class="rrow"><span>Total liabilities</span><span>'+money(debts)+'</span></div><div class="rrow"><span>Debt as % of assets</span><span>'+(assets?((debts/assets)*100).toFixed(1):'0.0')+'%</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
[('Net worth formula','Net worth equals total assets minus total liabilities.'),('Use consistent values','Use the same valuation date and reasonable current values for assets and outstanding balances for debts.'),('Important limitation','Some assets are difficult to value and taxes or selling costs can affect realizable value.')],
[('What counts as an asset?','Cash, investments, property and other items with measurable value can be included.'),('What counts as a liability?','Mortgages, loans, credit cards and other outstanding debts.'),('Can net worth be negative?','Yes, when liabilities exceed assets.'),('How often should I calculate it?','Periodic comparison can be useful if values and categories are kept consistent.')],[('debt-payoff-calculator.html','Debt payoff calculator'),('budget-percentage-calculator.html','Budget calculator'),('retirement-savings-calculator.html','Retirement savings calculator')])

page('break-even-calculator.html','Break-Even Calculator: Units, Revenue & Margin','Calculate contribution margin, break-even units, break-even revenue and profit at a selected sales volume.','Break-Even Calculator','Business calculator',[
 fld('Fixed costs ($)','fixed','20000','number','100','min="0"'),fld('Selling price per unit ($)','price','50','number','0.01','min="0.01"'),fld('Variable cost per unit ($)','variable','30','number','0.01','min="0"'),fld('Expected units sold','units','1500','number','1','min="0"')],common+'''function calc(){let f=n('fixed'),p=n('price'),v=n('variable'),u=n('units'),e=document.getElementById('err');if(bad([f,p,v,u])||f<0||p<=0||v<0||u<0||p<=v){e.hidden=false;e.textContent='Selling price must be greater than variable cost. Other values must be non-negative.';res.innerHTML='';return}e.hidden=true;let margin=p-v,be=f/margin,units=Math.ceil(be),revenue=units*p,profit=u*margin-f;res.innerHTML='<div class="rlabel">Break-even units</div><div class="rbig">'+units.toLocaleString()+'</div><div class="rrow"><span>Contribution margin</span><span>'+money(margin)+'/unit</span></div><div class="rrow"><span>Break-even revenue</span><span>'+money(revenue)+'</span></div><div class="rrow"><span>Profit at selected volume</span><span>'+money(profit)+'</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
[('Break-even formula','Break-even units equal fixed costs divided by selling price minus variable cost per unit.'),('Contribution margin','Each unit contributes selling price minus variable cost toward fixed costs and then profit.'),('Important limitation','Actual costs and prices can change. The model assumes constant unit economics within the selected range.')],
[('What if variable cost is higher than price?','The item has no positive contribution margin, so the simplified model cannot reach break-even.'),('Why round units up?','A fraction of a unit usually cannot be sold, so break-even units are rounded upward.'),('Does this include tax?','No, unless tax is already included in the entered costs.'),('Can I estimate profit?','Yes, enter expected units sold.')],[('markup-margin-calculator.html','Markup and margin calculator'),('roi-calculator.html','ROI calculator'),('price-per-unit-calculator.html','Unit price calculator')])

page('gpa-calculator.html','GPA Calculator: Courses, Credits & Grades','Calculate a weighted semester GPA from course credits and letter grades using a standard 4.0 scale.','GPA Calculator','Education calculator',[fld('Course 1 credits','c1','3','number','0.5','min="0"'),fld('Course 1 grade points','g1','4','number','0.1','min="0" max="4"'),fld('Course 2 credits','c2','4','number','0.5','min="0"'),fld('Course 2 grade points','g2','3','number','0.1','min="0" max="4"'),fld('Course 3 credits','c3','3','number','0.5','min="0"'),fld('Course 3 grade points','g3','3.7','number','0.1','min="0" max="4"'),fld('Course 4 credits','c4','0','number','0.5','min="0"'),fld('Course 4 grade points','g4','0','number','0.1','min="0" max="4"')],common+'''function calc(){let credits=[n('c1'),n('c2'),n('c3'),n('c4')],grades=[n('g1'),n('g2'),n('g3'),n('g4')],e=document.getElementById('err');if(bad(credits.concat(grades))||credits.some(x=>x<0)||grades.some(x=>x<0||x>4)){e.hidden=false;e.textContent='Credits must be non-negative and grade points must be between 0 and 4.';res.innerHTML='';return}let total=credits.reduce((a,b)=>a+b,0);if(total<=0){e.hidden=false;e.textContent='Enter credits for at least one course.';res.innerHTML='';return}e.hidden=true;let points=credits.reduce((s,c,i)=>s+c*grades[i],0),gpa=points/total;res.innerHTML='<div class="rlabel">Weighted semester GPA</div><div class="rbig">'+gpa.toFixed(2)+'</div><div class="rrow"><span>Total credits</span><span>'+total.toFixed(1)+'</span></div><div class="rrow"><span>Total quality points</span><span>'+points.toFixed(2)+'</span></div><div class="rrow"><span>Scale used</span><span>4.0</span></div>'}document.querySelectorAll('#fx input').forEach(x=>x.addEventListener('input',calc));calc();''',
[('GPA formula','Multiply each course grade point by its credits, add the quality points and divide by total credits.'),('Grade scale','Enter the grade-point value used by the institution. This calculator uses a maximum of 4.0.'),('Important limitation','Schools can use different scales, weighting, repeats and inclusion rules. Verify the official calculation policy.')],
[('Is GPA weighted by credits?','Yes. Courses with more credits contribute more to the result.'),('Can I use letter grades?','Convert each letter grade to the grade-point value used by the institution.'),('Does this calculate cumulative GPA?','This version calculates the entered set of courses. Existing cumulative totals can be combined as another weighted block in a future update.'),('Is every school on a 4.0 scale?','No. Check the institution policy.')],[('grade-percentage-calculator.html','Grade percentage calculator'),('percentage-calculator.html','Percentage calculator'),('blog.html','Fynzo guides')])

print('Built 8 SEO-focused calculators.')
