/* Fynzo shared UI — dark mode (light default), nav search, languages EN/FR/AR */
(function(){"use strict";
if(localStorage.getItem('fynzo-theme')==='dark') document.documentElement.setAttribute('data-theme','dark');
function toggleTheme(){var d=document.documentElement.getAttribute('data-theme')==='dark';if(d){document.documentElement.removeAttribute('data-theme');localStorage.setItem('fynzo-theme','light');}else{document.documentElement.setAttribute('data-theme','dark');localStorage.setItem('fynzo-theme','dark');}}
var T={fr:{"Calculators":"Calculatrices","Blog":"Blog","About":"À propos","Contact":"Contact","Start free":"Commencer","Tools":"Outils","Company":"Entreprise","Legal":"Légal","Finance":"Finance","Health":"Santé","FAQ":"FAQ","All tools":"Tous les outils","Mortgage":"Hypothèque","Loan":"Prêt","Compound interest":"Intérêts composés","Savings":"Épargne","Tax":"Impôt","Privacy":"Confidentialité","Terms":"Conditions","Disclaimer":"Avertissement","Free, fast, private calculators for the money and health decisions that matter.":"Des calculatrices gratuites, rapides et privées pour vos décisions d'argent et de santé.","Pick a calculator":"Choisissez une calculatrice","Type what you need — or browse below. Each tool has its own page with instant results.":"Tapez ce dont vous avez besoin — ou parcourez ci-dessous. Résultats instantanés.","Explore calculators →":"Explorer les calculatrices →","Read the guides":"Lire les guides","Free tools":"Outils gratuits","Sign-up time":"Inscription","Private in-browser":"Privé, navigateur","Frequently asked questions":"Questions fréquentes","Why Fynzo?":"Pourquoi Fynzo ?"},
ar:{"Calculators":"الحاسبات","Blog":"المدونة","About":"من نحن","Contact":"اتصل بنا","Start free":"ابدأ مجانًا","Tools":"الأدوات","Company":"الشركة","Legal":"قانوني","Finance":"المال","Health":"الصحة","FAQ":"الأسئلة","All tools":"كل الأدوات","Mortgage":"القرض العقاري","Loan":"القرض","Compound interest":"الفائدة المركبة","Savings":"الادخار","Tax":"الضريبة","Privacy":"الخصوصية","Terms":"الشروط","Disclaimer":"إخلاء المسؤولية","Free, fast, private calculators for the money and health decisions that matter.":"حاسبات مجانية وسريعة وخاصة لقرارات المال والصحة المهمة.","Pick a calculator":"اختر حاسبة","Type what you need — or browse below. Each tool has its own page with instant results.":"اكتب ما تحتاجه — أو تصفّح بالأسفل. نتائج فورية.","Explore calculators →":"استكشف الحاسبات ←","Read the guides":"اقرأ الأدلة","Free tools":"أدوات مجانية","Sign-up time":"وقت التسجيل","Private in-browser":"خاص في المتصفح","Frequently asked questions":"الأسئلة الشائعة","Why Fynzo?":"لماذا Fynzo؟"}};
var SEL='.nav-links a, .foot h4, .foot a, .foot-brand p, .sec-head h2, .filter, .hero-actions .btn, .trust small, .prose h2';
function applyLang(lang){var d=T[lang];
document.querySelectorAll(SEL).forEach(function(el){if(!el.hasAttribute('data-en'))el.setAttribute('data-en',el.textContent.trim());var en=el.getAttribute('data-en');if(lang==='en'){el.textContent=en;}else if(d&&d[en]){el.textContent=d[en];}});
var h1=document.querySelector('.hero h1');if(h1){if(lang==='fr')h1.innerHTML='Toutes vos <span>calculatrices</span> d\'argent et de santé — en un seul endroit.';else if(lang==='ar')h1.innerHTML='كل <span>حاسبات</span> المال والصحة — في مكان واحد.';else h1.innerHTML='All your money &amp; health <span>calculators</span> — in one place.';}
var hp=document.querySelector('.hero p');if(hp){if(lang==='fr')hp.textContent='12 calculatrices gratuites, rapides et privées. Une réponse claire en quelques secondes. Sans inscription.';else if(lang==='ar')hp.textContent='12 حاسبة مجانية وسريعة وخاصة. نتيجة واضحة في ثوانٍ. بدون تسجيل.';else hp.textContent='12 free, fast and private calculators. Estimate a mortgage, plan your savings, check your BMI — a clear answer in seconds. No sign-up, ever.';}
var cs=document.getElementById('calcSearch');if(cs){cs.placeholder=lang==='fr'?'Rechercher — ex. « hypothèque », « IMC »...':lang==='ar'?'ابحث — جرّب «قرض»، «مؤشر كتلة الجسم»...':'Search a calculator — try "mortgage", "BMI", "loan"...';}
document.documentElement.setAttribute('lang',lang);if(lang==='ar')document.documentElement.setAttribute('dir','rtl');else document.documentElement.removeAttribute('dir');localStorage.setItem('fynzo-lang',lang);}
function build(){var nl=document.querySelector('.nav-links');if(!nl)return;var w=document.createElement('div');w.className='nav-tools';
w.innerHTML='<div class="nav-search" id="navSearch"><input type="text" placeholder="Search…" aria-label="Search"><button class="go" aria-label="Go"><svg viewBox="0 0 24 24" fill="none"><path d="M5 12 H19 M13 6 L19 12 L13 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div><button class="icon-btn" id="searchToggle" aria-label="Search"><svg viewBox="0 0 24 24" fill="none"><circle cx="11" cy="11" r="7" stroke="currentColor" stroke-width="2"/><path d="M20 20 L16 16" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></button><button class="icon-btn" id="themeToggle" aria-label="Theme"><svg class="sun" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="4.5" stroke="currentColor" stroke-width="2"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5L19 19M19 5l-1.5 1.5M6.5 17.5L5 19" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg><svg class="moon" viewBox="0 0 24 24" fill="none"><path d="M20 14.5 A8 8 0 1 1 9.5 4 A6.5 6.5 0 0 0 20 14.5 Z" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg></button><select class="lang-select" id="langSelect" aria-label="Language"><option value="en">EN</option><option value="fr">FR</option><option value="ar">AR</option></select>';
nl.appendChild(w);
var box=w.querySelector('#navSearch'),inp=box.querySelector('input');
w.querySelector('#searchToggle').addEventListener('click',function(){box.classList.toggle('open');if(box.classList.contains('open'))inp.focus();});
function go(){var q=inp.value.trim();if(!q)return;if(document.getElementById('calcSearch')){var cs=document.getElementById('calcSearch');cs.value=q;cs.dispatchEvent(new Event('input'));document.getElementById('tools').scrollIntoView({behavior:'smooth'});}else{window.location='index.html?q='+encodeURIComponent(q)+'#tools';}}
inp.addEventListener('keydown',function(e){if(e.key==='Enter')go();});box.querySelector('.go').addEventListener('click',go);
w.querySelector('#themeToggle').addEventListener('click',toggleTheme);
var ls=w.querySelector('#langSelect'),sl=localStorage.getItem('fynzo-lang')||'en';ls.value=sl;ls.addEventListener('change',function(){applyLang(ls.value);});applyLang(sl);}
function qp(){var cs=document.getElementById('calcSearch');if(!cs)return;var q=new URLSearchParams(location.search).get('q');if(q){cs.value=q;cs.dispatchEvent(new Event('input'));var t=document.getElementById('tools');if(t)setTimeout(function(){t.scrollIntoView({behavior:'smooth'});},200);}}
document.addEventListener('DOMContentLoaded',function(){build();qp();});
})();
